@tool
extends Node2D

# The sun and the air of one level: a CanvasModulate that decides how dark the world sits, and a
# DirectionalLight2D that puts light back onto whatever faces the sun and drops a shadow behind
# everything that doesn't. Drop it into a level, pick a preset, and tune from there.
#
# A preset rather than eight loose numbers because the numbers are not independent - a warm low sun
# only reads as evening against a cool dim ambient, and the same sun over a bright neutral ambient
# reads as a lighting bug. The presets are those pairings; the knobs under them are for taste.
#
# @tool so the level looks in the editor the way it will look in game. Nothing here touches game
# state, so running in the editor costs nothing but the redraw.
#
# What actually casts the shadows is the tilesets' occlusion layer, generated by
# tools/lighting/tile_occluder_gen.gd. A level whose terrain casts nothing has almost certainly had
# new tiles painted since that was last run.

enum Preset {
	DAY,
	GOLDEN_HOUR,
	DUSK,
	NIGHT,
	INTERIOR,
}

# `sun_angle` is the direction the light travels, in degrees, and 0 is straight down: at +55 the sun
# sits up and to the right and shadows are thrown down and to the left, which is the low sun a rider
# heading east has in front of them. Negative puts it behind them instead.
#
# `ambient` is what everything is multiplied down to before any light is added back, so it is really
# the colour of shadow - cool against a warm sun, or the whole mood stops reading as sunlight.
const PRESETS := {
	Preset.DAY: {
		"ambient": Color(0.88, 0.86, 0.84),
		"sun_color": Color(1.0, 0.97, 0.9),
		"sun_energy": 0.3,
		"sun_angle": 20.0,
	},
	Preset.GOLDEN_HOUR: {
		"ambient": Color(0.62, 0.56, 0.6),
		"sun_color": Color(1.0, 0.78, 0.45),
		"sun_energy": 0.85,
		"sun_angle": 55.0,
	},
	Preset.DUSK: {
		"ambient": Color(0.38, 0.35, 0.48),
		"sun_color": Color(0.95, 0.5, 0.34),
		"sun_energy": 0.55,
		"sun_angle": 72.0,
	},
	Preset.NIGHT: {
		"ambient": Color(0.2, 0.22, 0.34),
		"sun_color": Color(0.55, 0.65, 0.95),
		"sun_energy": 0.16,
		"sun_angle": -25.0,
	},
	# No sun at all - a room's light comes from its lamps and whatever falls through the door.
	Preset.INTERIOR: {
		"ambient": Color(0.36, 0.31, 0.29),
		"sun_color": Color(1.0, 0.9, 0.7),
		"sun_energy": 0.0,
		"sun_angle": 0.0,
	},
}

@export var preset : Preset = Preset.GOLDEN_HOUR : set = set_preset

@export_group("Fine tuning")
# Scales the preset's ambient without touching its colour, which is the one knob worth reaching for
# first: the same evening a shade lighter or darker.
@export_range(0.0, 2.0, 0.01) var ambient_brightness : float = 1.0 : set = set_ambient_brightness
@export_range(0.0, 3.0, 0.01) var sun_strength : float = 1.0 : set = set_sun_strength
# Swings the sun without leaving the preset - shorter shadows at noon, or the sun over the other
# shoulder for a level the player crosses westward.
@export_range(-180.0, 180.0, 1.0) var sun_angle_offset : float = 0.0 : set = set_sun_angle_offset
# Off is cheaper and flatter. Worth turning off for a level with nothing solid to cast one.
@export var sun_shadows : bool = true : set = set_sun_shadows


func set_preset(value : Preset) -> void:
	preset = value
	_apply()


func set_ambient_brightness(value : float) -> void:
	ambient_brightness = value
	_apply()


func set_sun_strength(value : float) -> void:
	sun_strength = value
	_apply()


func set_sun_angle_offset(value : float) -> void:
	sun_angle_offset = value
	_apply()


func set_sun_shadows(value : bool) -> void:
	sun_shadows = value
	_apply()


func _ready() -> void:
	_apply()


# Setters fire while the scene is still loading, before the two children exist, so everything is
# applied again from _ready() rather than relying on the order the properties happen to arrive in.
func _apply() -> void:
	if not is_node_ready():
		return

	var values : Dictionary = PRESETS[preset]

	var ambient := get_node_or_null("Ambient") as CanvasModulate
	if ambient != null:
		var tint : Color = values["ambient"]
		# Alpha is left alone deliberately: a CanvasModulate's alpha would make the whole world
		# see-through rather than dark, and there is nothing behind it but the clear colour.
		ambient.color = Color(
			tint.r * ambient_brightness,
			tint.g * ambient_brightness,
			tint.b * ambient_brightness,
			1.0)

	var sun := get_node_or_null("Sun") as DirectionalLight2D
	if sun != null:
		var energy : float = values["sun_energy"] * sun_strength
		sun.color = values["sun_color"]
		sun.energy = energy
		sun.rotation_degrees = values["sun_angle"] + sun_angle_offset
		# A sun at zero energy still costs a shadow pass over every occluder on screen for light
		# nobody can see, so an interior switches it off outright rather than turning it down.
		sun.visible = energy > 0.0
		sun.shadow_enabled = sun_shadows and energy > 0.0
